name: 🏁 Windows Builds
on:
  workflow_call:

# Global Settings
env:
  # Only used for the cache key. Increment version to force clean build.
  GODOT_BASE_BRANCH: 3.x
  SCONSFLAGS: verbose=yes warnings=no werror=no debug_symbols=no use_mingw=yes

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-windows
  cancel-in-progress: true

jobs:
  build-windows:
    runs-on: "ubuntu-22.04"
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Editor w/ Mono (target=release_debug, tools=yes)
            cache-name: windows-editor-mono
            target: release_debug
            tools: true
            sconsflags: module_mono_enabled=yes
            bin: "./bin/godot.windows.opt.tools.64.mono.exe"
            build-mono: true

          - name: Template w/ Mono (target=release, tools=no)
            cache-name: windows-template-mono
            target: release
            tools: false
            sconsflags: module_mono_enabled=yes
            bin: "./bin/godot.windows.opt.64.mono.exe"
            build-mono: false

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependenecies & Setup
        shell: bash
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update

          sudo apt-get install --no-install-recommends -y \
            mingw-w64 wine64 wine32 wine xvfb unzip wget build-essential pkg-config libx11-dev \
              libxcursor-dev libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev \
              libpulse-dev libdbus-1-dev libudev-dev libxi-dev libxrandr-dev yasm xvfb wget unzip \
              libspeechd-dev speech-dispatcher scons


          sudo update-alternatives --set x86_64-w64-mingw32-gcc /usr/bin/x86_64-w64-mingw32-gcc-posix
          sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix

          mkdir -p mono_win64/lib

          # Download the SDK (Headers and static libs)
          wget https://github.com/godotengine/godot-mono-builds/releases/download/release-ae49eba/windows-x86_64.zip
          unzip -q windows-x86_64.zip -d mono_win64


          wget https://github.com/godotengine/godot-mono-builds/releases/download/release-ae49eba/bcl-desktop-win32.zip
          unzip -q bcl-desktop-win32.zip -d temp_bcl

          # Find the exact folder containing mscorlib.dll inside temp_bcl
          BCL_SRC=$(dirname $(find temp_bcl -name "mscorlib.dll" | head -n 1))
          echo "Found BCL at: $BCL_SRC"

          # Create the exact path SCons wants and copy everything in
          mkdir -p mono_win64/desktop-windows-x86_64-release/lib/mono/4.5
          cp -r "$BCL_SRC"/* mono_win64/desktop-windows-x86_64-release/lib/mono/4.5/

          # Clean up
          rm -rf temp_bcl bcl-desktop-win32.zip



      - name: Download Mono Glue
        uses: actions/download-artifact@v4
        with:
          name: godot-mono-glue
          path: modules/mono/glue

      # Pass 2: Rebuild with glue
      - name: Compilation (mono_glue=yes)
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} ${{ matrix.sconsflags }} mono_glue=yes mono_prefix=${{ github.workspace }}/mono_win64/desktop-windows-x86_64-release mono_static=yes copy_mono_root=yes
          platform: windows
          target: ${{ matrix.target }}
          tools: ${{ matrix.tools }}

      # Package the artifact
      - name: Prepare artifact
        shell: bash
        run: |
          # Clean up unnecessary compiler files (.lib, .exp)
          rm -f bin/*.exp bin/*.lib bin/*.pdb

          # Strip the Windows executable to save size
          x86_64-w64-mingw32-strip bin/*.exe || true

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        with:
          name: ${{ matrix.cache-name }}
